name: Build Pi Image
on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]
jobs:
  build-pi:
    strategy:
      matrix:
        branch: [arm64, master]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: RPi-Distro/pi-gen
          ref: ${{ matrix.branch }}
      - uses: actions/checkout@v4
        with:
          path: main
      - run: sudo apt-get update
      - run: sudo apt-get install -y rename coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz arch-test
      - name: Run pi-gen
        run: |
          cp -r main/pi/* .
          sudo ./build.sh
          sudo rename -n 's/raspios/turtle/g' deploy/*.img.xz
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.branch }} image
          path: deploy/*.img.xz
      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          files: deploy/*.img.xz

